# Generated by Django 3.2.18 on 2023-05-25 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ekycvideo',
            table='video_info',
        ),
    ]
